### ISSUE TITLE
Can't build m4ri library on Windows.

### ISSUE THREAD

**Issue by BillUtada** [thomwiggers/lpn#3]
when I build this project with cargo, it gives error message as below. What's the problem here? thx.

`    Updating crates.io index
   Compiling m4ri-sys v0.3.0
   Compiling vob v2.0.2
   Compiling serde_json v1.0.39
error: failed to run custom build command for `m4ri-sys v0.3.0`

Caused by:
  process didn't exit successfully: `D:\lpn-master\target\debug\build\m4ri-sys-f3a9b8bdc67f3908\build-script-build` (exit code: 101)
--- stdout
Making M4RI
PWD: "C:\\Users\\u\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\m4ri-sys-0.3.0"
cargo:warning=Building m4ri lib
Configuring build!

--- stderr
thread 'main' panicked at 'Failed to execute: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:999:5`

**Comment by thomwiggers** [comment]
So the `build.rs` really assumes it's running on Linux: I hardcoded `/usr/bin/` paths for `autoreconf` , etc. Also, as far as I can tell in the few minutes I looked at it, getting `autoreconf` on Windows involves getting cygwin or doing complicated things.

As I also do not have any Windows machines, and can't invest the amount time needed to debug this issue, I'm afraid I can't fix this issue.

PRs that improve support for non-Linux systems are welcome.  For now, this means that Windows is not supported.

**Comment by thomwiggers** [comment]
I pushed a commit to the [`m4ri-sys` repo](/thomwiggers/m4ri-rust/) to not have hardcoded paths; you could try building `m4ri-rust` on Windows from Git and see if it helps.

**Comment by BillUtada** [comment]
thanks for your reply! but I have to say that I tried on both windows and linux(ubuntu 18.04), even MacOS, All three platforms will give this error!

My setup steps are install rust&cargo => clone git repo => cargo build, if that helps.

**Comment by thomwiggers** [comment]
You may need to install some of the build dependencies of m4ri. Try installing `build-essential` on Ubuntu.

**Comment by thomwiggers** [comment]
I also pushed a new release of m4ri-sys that should provide better feedback.

**Comment by BillUtada** [comment]
Well, I tried it with many linux machine, and all of them will give this error. I'm sure build essential is properly installed, also rust-libc kinda thing.

**Comment by BillUtada** [comment]
I'm almost new to rust,but as far as I'm concerned, this may because I forgot to install some dependency, but I have no idea what it is.

**Comment by thomwiggers** [comment]
Can you run `cargo update` and then `cargo build`? The error you get should be slightly more specific now when you build `m4ri-sys` 0.3.1. (should now say "failed to execute **tool**").

**Comment by BillUtada** [comment]
update is no use. And yes, now it says failed to execute autoreconf.

> error: failed to run custom build command for `m4ri-sys v0.3.1 (/root/m4ri-rust/m4ri-sys)`
> process didn't exit successfully: `/root/m4ri-rust/target/debug/build/m4ri-sys-e95a5c667ec23827/build-script-build` (exit code: 101)
> --- stdout
> Making M4RI
> PWD: "/root/m4ri-rust/m4ri-sys"
> cargo:warning=Building m4ri lib
> Configuring build!
> 
> --- stderr
> thread 'main' panicked at 'Failed to execute autoreconf: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
> note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by thomwiggers** [comment]
Ok, then `build-essential` apparently does not include `autoreconf`.

Consider running the following:

```sh
apt-get install automake autoconf
```

**Comment by BillUtada** [comment]
worked! thank you so much~~ :)
