### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ganlubbq** [thomwiggers/lpn#9]
I have one trouble
Caused by:
  process didn't exit successfully: `F:\lpn\target\release\build\m4ri-sys-fde8ea733e4716a7\build-script-build` (exit code: 101)
Making M4RI
PWD: "C:\\Users\\lenovo\\.cargo\\registry\\src\\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\\m4ri-sys-0.3.2"
cargo:warning=Building m4ri lib
Configuring build!

--- stderr
thread 'main' panicked at 'Failed to execute autoreconf: Os { code: 2, kind: NotFound, message: "system can not find the file"
 }', src\libcore\result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

rustup 1.21.1 (2019-12-20)
x86_64-pc-windows-gnu

**Comment by thomwiggers** [comment]
The `m4ri-rust` dependency does not support Windows for now, unfortunately.

See https://github.com/thomwiggers/m4ri-rust/issues/6
